### ISSUE TITLE
pets interface issue

### ISSUE THREAD

**Issue by stage1st** [obble/modui_classic#38]
<img width="500" alt="Screen Shot 2019-09-01 at 2 49 17 PM" src="https://user-images.githubusercontent.com/54734593/64072829-002d3900-ccc8-11e9-8e42-52b6137a9c1c.png">

i guess u need to put back, Old school of Status Test is awesome.

![ufoirc3](https://user-images.githubusercontent.com/54734593/64072879-d58fb000-ccc8-11e9-9049-c45724d80cc4.png)

**Comment by stage1st** [comment]
post a update, sry man
<img width="500" alt="Screen Shot 2019-09-01 at 3 13 54 PM" src="https://user-images.githubusercontent.com/54734593/64073040-4df77080-cccb-11e9-9b87-309c7076c2d0.png">

**Comment by obble** [comment]
thanks, it looks like the second image all the time now? looks like the background offset is wrong - i'll fix it today

**Comment by stage1st** [comment]
> thanks, it looks like the second image all the time now? looks like the background offset is wrong - i'll fix it today

ya, thanks for your work, love it.

anyway, how about Status Test? pet's and player's.

**Comment by obble** [comment]
oh yeah sorry - it is on my to-do list :)

**Comment by stage1st** [comment]
and this one goona be online later?

means CD on Nameplates
![1aae86d878c41de86cd9c7045a8ad93c](https://user-images.githubusercontent.com/54734593/64074215-1db7ce00-ccdb-11e9-9422-d6f36f54eae5.png)

always be here for you work.

**Comment by obble** [comment]
cooldowns on nameplates are there as cooldown spirals now - i might add numbers soon

**Comment by obble** [comment]
I think the pet bar thing should be fixed now? let me know if its still off where it should be positioned by reopening this ticket

**Comment by stage1st** [comment]
nope,just delete WTF and replace modui_Classic, nothing happened.
![捕获](https://user-images.githubusercontent.com/54734593/64079011-8cfde400-cd14-11e9-84fe-4635cf138104.PNG)

**Comment by stage1st** [comment]
get some details i think

when left actionbar on, its good, i think.

![捕获](https://user-images.githubusercontent.com/54734593/64079061-4957aa00-cd15-11e9-8e80-9993f0ff7783.PNG)
![捕获2](https://user-images.githubusercontent.com/54734593/64079064-4d83c780-cd15-11e9-9e4e-a0547a118f75.PNG)

**Comment by stage1st** [comment]
@obble still get issue for pets interface.

<img width="750" alt="Screen Shot 2019-09-03 at 10 24 52 AM" src="https://user-images.githubusercontent.com/54734593/64140749-1b1ebb00-ce38-11e9-9aaa-a89f356897d4.png">

anyway, sometimes the bag interface will be not good.
